name: build

on:
  push: {branches: master}
  pull_request: {branches: master}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: sample-app
    name: Echo
    steps:
      - name: check environment
        run: echo ${{ env.IMAGE_NAME }}
      - name: check build tools and folder structure
        run: |
          ls
          pwd
          cmake --version
          make --version
      - name: build project
        run: |
          cd ..
          ls
          pwd
      - name: run the executable
        run: |
          ls
          pwd
